/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.15
 * Generated at: 2023-01-15 17:00:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class services_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<body>\r\n");
      out.write("<style>\r\n");
      out.write(".content-table\r\n");
      out.write("{\r\n");
      out.write("border-collapse:collapse;\r\n");
      out.write("margin:25px 0;\r\n");
      out.write("font-size:0.9cn;\r\n");
      out.write("min-width:400px;\r\n");
      out.write("border-spacing:0;\r\n");
      out.write("text-align:center;\r\n");
      out.write("font-radius:5px 5px 0 0;\r\n");
      out.write("overflow:hidden;\r\n");
      out.write("box-shadow:0 0 20px rgba(0,0,0,0.15);\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".content-table thead tr\r\n");
      out.write("{\r\n");
      out.write("  background-color:#009879;\r\n");
      out.write("  color:#fffffff;\r\n");
      out.write("  text-align:left;\r\n");
      out.write("  font-weight:bold;\r\n");
      out.write("  font-size:18px;\r\n");
      out.write("}\r\n");
      out.write(" th\r\n");
      out.write(" {\r\n");
      out.write("   padding:10px 20px;\r\n");
      out.write("   \r\n");
      out.write("}\r\n");
      out.write(".ttbody tr\r\n");
      out.write("{\r\n");
      out.write(" border-bottom:1px solid #dddddd;\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("} \r\n");
      out.write(".ttbody tr:first-of-type\r\n");
      out.write("{\r\n");
      out.write("background-color:#;\r\n");
      out.write("}\r\n");
      out.write(".ttbody tr:last-of-type\r\n");
      out.write("{\r\n");
      out.write(" border-bottom:1px solid black;\r\n");
      out.write("}\r\n");
      out.write(".ttbody tr.active-row\r\n");
      out.write("{\r\n");
      out.write("font-weight:bold;\r\n");
      out.write("color:#009879;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");

try
{
	Class.forName("com.mysql.cj.jdbc.Driver");
	Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/medical","root","madhuri@2001");
	Statement stat=con.createStatement();
	ResultSet rs=stat.executeQuery("select * from billform7");
	out.println("<center><h2> Medical Invoice</h2></center>");
    out.println("<hr>");
    out.println("<center><table class='content-table' >");
    out.println("<thead><tr><th>Quantity</th> <th>Item Name</th><th>MFG</th><th>Batch No.</th><th>M.R.P.</th><th>Exp.Date</th><th>Rate</th><th>Amount Rs.</th></tr></thead>");
    while(rs.next())
    {
	
      out.write("\r\n");
      out.write("\t<tbody class=\"ttbody\">\r\n");
      out.write("    <tr class='active-row'>\r\n");
      out.write("\t<th scope=\"row\"> ");
      out.print(rs.getString(1));
      out.write("</th>\r\n");
      out.write("\t\t<th scope=\"row\"> ");
      out.print(rs.getString(2));
      out.write("</th>\r\n");
      out.write("\t\t<th scope=\"row\"> ");
      out.print(rs.getString(3));
      out.write("</th>\r\n");
      out.write("\t\t<th scope=\"row\"> ");
      out.print(rs.getString(4));
      out.write("</th>\r\n");
      out.write("\t\t<th scope=\"row\"> ");
      out.print(rs.getDouble(5));
      out.write("</th>\r\n");
      out.write("\t\t<th scope=\"row\"> ");
      out.print(rs.getString(6));
      out.write("</th>\r\n");
      out.write("\t\t<th scope=\"row\"> ");
      out.print(rs.getFloat(7));
      out.write("</th>\r\n");
      out.write("\t\t<th scope=\"row\"> ");
      out.print(rs.getFloat(8));
      out.write("</th>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t</tbody>\r\n");
      out.write("\t\r\n");
      out.write("\t");

    }		
	rs.close();
	con.close();
	out.println("</center></table>");
		
}
catch(Exception e)
{
	out.println(e);
}

      out.write("\r\n");
      out.write("<button><a href=\"service.html\">Edit</a></button>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
