/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.15
 * Generated at: 2023-01-19 12:43:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ViewPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write(" <!DOCTYPE html>\r\n");
      out.write("<!-- Created By CodingNepal - www.codingnepalweb.com -->\r\n");
      out.write("<html lang=\"en\" dir=\"ltr\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <!------<title> Website Layout | CodingLab</title>------>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"1.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css\"/>\r\n");
      out.write("   </head>\r\n");
      out.write("<body>\r\n");
      out.write("<style>\r\n");
      out.write("@charset \"ISO-8859-1\";\r\n");
      out.write("@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700&display=swap');\r\n");
      out.write("*{\r\n");
      out.write("  margin: 0;\r\n");
      out.write("  padding: 0;\r\n");
      out.write("  box-sizing: border-box;\r\n");
      out.write("  font-family: 'Poppins',sans-serif;\r\n");
      out.write("}\r\n");
      out.write("::selection{\r\n");
      out.write("  color: #000;\r\n");
      out.write("  background: #fff;\r\n");
      out.write("}\r\n");
      out.write("nav{\r\n");
      out.write("  position: fixed;\r\n");
      out.write("  background: #1b1b1b;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  padding: 10px 0;\r\n");
      out.write("  z-index: 12;\r\n");
      out.write("}\r\n");
      out.write("nav .menu{\r\n");
      out.write("  max-width: 1250px;\r\n");
      out.write("  margin: auto;\r\n");
      out.write("  display: flex;\r\n");
      out.write("  align-items: center;\r\n");
      out.write("  justify-content: space-between;\r\n");
      out.write("  padding: 0 20px;\r\n");
      out.write("}\r\n");
      out.write(".menu .logo a{\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  font-family:cursive;\r\n");
      out.write("  color: white;\r\n");
      out.write(" \r\n");
      out.write("}\r\n");
      out.write(".menu .logo img\r\n");
      out.write("{\r\n");
      out.write("    width:70px;\r\n");
      out.write("\tmargin-right:10px;\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write(".menu ul{\r\n");
      out.write("  display: inline-flex;\r\n");
      out.write("}\r\n");
      out.write(".menu ul li{\r\n");
      out.write("  list-style: none;\r\n");
      out.write("  margin-left: 7px;\r\n");
      out.write("}\r\n");
      out.write(".menu ul li:first-child{\r\n");
      out.write("  margin-left: 0px;\r\n");
      out.write("}\r\n");
      out.write(".menu ul li a{\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  color: #fff;\r\n");
      out.write("  font-size: 18px;\r\n");
      out.write("  font-weight: 500;\r\n");
      out.write("  padding: 8px 15px;\r\n");
      out.write("  border-radius: 5px;\r\n");
      out.write("  transition: all 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write(".menu ul li a:hover{\r\n");
      out.write("  background:white;\r\n");
      out.write("  color: black;\r\n");
      out.write("}\r\n");
      out.write(".img{\r\n");
      out.write("  background-image: url(\"home2.jpg\");\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  height: 100vh;\r\n");
      out.write("  background-size: cover;\r\n");
      out.write("  background-position: center;\r\n");
      out.write("  position: relative;\r\n");
      out.write("}\r\n");
      out.write(".img::before{\r\n");
      out.write("  content: '';\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  height: 100%;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("}\r\n");
      out.write(".center{\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  top: 28%;\r\n");
      out.write("  left: 20%;\r\n");
      out.write("  transform: translate(-50%, -50%);\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  padding: 0 20px;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("}\r\n");
      out.write(".center .title{\r\n");
      out.write("  color:teal;\r\n");
      out.write("  font-size: 50px;\r\n");
      out.write("  font-weight: 600;\r\n");
      out.write("  margin:-0%;\r\n");
      out.write("}\r\n");
      out.write(".center .sub_title{\r\n");
      out.write("  color: #fff;\r\n");
      out.write("  font-size: 52px;\r\n");
      out.write("  font-weight: 600;\r\n");
      out.write("}\r\n");
      out.write(".center .btns{\r\n");
      out.write("  margin-top: 20px;\r\n");
      out.write("}\r\n");
      out.write(".center .btns button{\r\n");
      out.write("  height: 40px;\r\n");
      out.write("  width: 170px;\r\n");
      out.write("  border-radius: 5px;\r\n");
      out.write("  border: none;\r\n");
      out.write("  margin: 0 10px;\r\n");
      out.write("  border: 2px solid white;\r\n");
      out.write("  font-size: 17px;\r\n");
      out.write("  font-weight: 500;\r\n");
      out.write("  padding: 0 10px;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  outline: none;\r\n");
      out.write("  transition: all 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write(".center .btns button:first-child{\r\n");
      out.write("  color: black;\r\n");
      out.write("  background: none;\r\n");
      out.write("}\r\n");
      out.write(".btns button:first-child:hover{\r\n");
      out.write("  background: white;\r\n");
      out.write("  color: black;\r\n");
      out.write("}\r\n");
      out.write(".center .btns button:last-child{\r\n");
      out.write("  background: white;\r\n");
      out.write("  color: black;\r\n");
      out.write("}\r\n");
      out.write(".logo a:hover\r\n");
      out.write("{\r\n");
      out.write(" \r\n");
      out.write("  border-radius: 2px;\r\n");
      out.write("  transition: all 0.3s ease;\r\n");
      out.write("  border-radius: 5px;\r\n");
      out.write("  border: none;\r\n");
      out.write("  border: 1px solid white;\r\n");
      out.write("  font-size: 15px;\r\n");
      out.write("  font-weight: 500;\r\n");
      out.write("  padding: 0 10px;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  outline: none;\r\n");
      out.write("  transition: all 0.3s ease;\r\n");
      out.write("  \r\n");
      out.write("}\r\n");
      out.write(" \r\n");
      out.write("</style>\r\n");
      out.write("  <nav>\r\n");
      out.write("    <div class=\"menu\">\r\n");
      out.write("      <div class=\"logo\">\r\n");
      out.write("      <img src=\"logo.png\">\r\n");
      out.write("       \r\n");
      out.write("      </div>\r\n");
      out.write("      <ul>\r\n");
      out.write("        <li><a href=\"home.jsp\">Home</a></li>\r\n");
      out.write("        <li><a href=\"About.jsp\">About</a></li>\r\n");
      out.write("        <li><a href=\"services.jsp\">Services</a>\r\n");
      out.write("        <li><a href=\"contact.jsp\">Contact_Us</a></li>\r\n");
      out.write("        <li><a href=\"Address.jsp\">Address</a></li>\r\n");
      out.write("        \r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("  </nav>\r\n");
      out.write("  <div class=\"img\"></div>\r\n");
      out.write("  <div class=\"center\">\r\n");
      out.write("    <div class=\"title\"> Medical Store</div>\r\n");
      out.write("    <div class=\"sub_title\"></div>\r\n");
      out.write("    <div class=\"btns\">\r\n");
      out.write("      \r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write(" ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
